data_home: /Users/melvinenargeot/Data/benchmark_inverse_problems
data_paths:
    generated_datasets: generated_datasets
    generated_trainings: generated_training
    BSD500: BSD500/BSR/BSDS500/data/images